### ISSUE TITLE
Lightline tab icon color

### ISSUE THREAD

**Issue by vurtune** [bryanmylee/vim-colorscheme-icons#1]
Hey, nice plugin.
There is a way to make tab icons with different colors?
I'm using vim-devicons, onedark colorscheme and lightline.vim with this function:

```
function! LightlineWebDevIcons(n)
  let l:bufnr = tabpagebuflist(a:n)[tabpagewinnr(a:n) - 1]
  return WebDevIconsGetFileTypeSymbol(bufname(l:bufnr))
endfunction
```

![20210804_162722](https://user-images.githubusercontent.com/74165007/128257273-18f520f2-ad04-4dbb-ab87-8e8ba0315291.jpg)

**Comment by bryanmylee** [comment]
Hi, I'm not too sure about customizing the colors for `lightline.vim`.

This plugin specifically only targets the font color of the Nerd font icons. You will have to ask the developers at `lightline.vim`.
